lms/urls.py
from django.urls import path

from . import views

app_name = 'lms'
urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contato, name='contato')
]

lmsimpacta/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lms.urls')),
    path('', include('contas.urls')),
    path('cursos/', include('curriculo.urls')),
    path('restrito/', include('restrito.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restrito/urls.py
from django.urls import path

from . import views

app_name = 'restrito'
urlpatterns = [
    path('', views.home, name='home'),
    path('matriculas/', views.matricula_lista, name="matricula_lista"),
    path('matriculas/solicitar/', views.matricula_solicitar, name="matricula_solicitar"),
    path('matriculas/solicitar/<int:id_do>/', views.matricula_solicitar, name="matricula_solicitar"),
    path('matriculas/remover/<int:id_sm>/', views.matricula_remover, name="matricula_remover"),
    path('turma/<int:id_do>/', views.turma, name='turma'),
    path('turma/<int:id_do>/atividade/', views.atividade_vinculada_form, name='vinculada_form'),
    path('turma/<int:id_do>/atividade/<int:id_vin>/', views.atividade_vinculada_form, name='vinculada_form'),
    path('turma/<int:id_do>/atividade/<int:id_vin>/remover/', views.atividade_vinculada_remover, name='vinculada_remover'),
    path('turma/<int:id_do>/atividade/<int:id_vin>/entregas/', views.entrega_listar, name='entrega_lista'),
    path('turma/<int:id_do>/atividade/<int:id_vin>/entregar/', views.entrega_form, name='entrega_form'),
    path('atividades/', views.atividade_lista, name='atividade_lista'),
    path('atividades/form/', views.atividade_form, name='atividade_form'),
    path('atividades/form/<int:id>/', views.atividade_form, name='atividade_form'),
    path('atividades/remover/<int:id>/', views.atividade_remover, name='atividade_remover'),
    
]

curriculo/models/turmas.py
from django.db import models

class Turma(models.Model):
    ano = models.IntegerField()
    semestre = models.IntegerField()
    nome = models.CharField(max_length=1)

    def __str__(self):
        return "{}-{}-{}".format(self.ano, self.semestre, self.nome)

    class Meta:
        unique_together = ("ano", "semestre", "nome")

restrito/models/atividades.py
from django.db import models

class Atividade(models.Model):
    TIPO_ATIVIDADE = (
        ('RESPOSTA ABERTA', 'Resposta Aberta'),
        ('TESTE', 'Teste')
    )

    titulo = models.CharField(max_length=255, unique=True)
    descricao = models.TextField(max_length=500, default=None, blank=True, null=True)
    conteudo = models.TextField(max_length=255)
    tipo = models.CharField(max_length=20, choices=TIPO_ATIVIDADE)
    extras = models.CharField(max_length=250, default=None, blank=True, null=True)
    professor = models.ForeignKey("contas.Professor", on_delete=models.PROTECT)

    def __str__(self):
        return self.titulo

restrito/models/atividades_vinculadas.py
from django.db import models
from django.db.models import Prefetch
from django.db.models.query import QuerySet

from .entregas import Entrega

class AtividadeVinculadaQuerySet(QuerySet):

    def listar_atividades_turma(self, usuario, do):
        qs = self.filter(disciplina_ofertada=do)
        if usuario.tipo == 'A':
            qs.prefetch_related(
                Prefetch(
                    "entrega_set",
                    queryset=Entrega.objects.filter(aluno=usuario.aluno),
                    to_attr="entrega"
                )
            )
        elif usuario.tipo == 'P':
            qs.annotate(entregas=models.Count('entrega'))
        return qs

class AtividadeVinculada(models.Model):
    STATUS = (
        ('DISPONIBILIZADA','Disponibilizada'),
        ('ABERTA','Aberta'),
        ('FECHADA','Fechada'),
        ('ENCERRADA','Encerrada'),
        ('PRORROGADA','Prorrogada')
    )

    atividade = models.ForeignKey("restrito.Atividade",on_delete=models.PROTECT)
    professor = models.ForeignKey("contas.Professor", on_delete=models.PROTECT)
    disciplina_ofertada = models.ForeignKey("curriculo.DisciplinaOfertada", on_delete=models.PROTECT)
    rotulo = models.CharField(max_length=255)
    status = models.CharField(max_length=20, choices=STATUS)
    data_inicio = models.DateTimeField()
    data_fim = models.DateTimeField()

    objects = AtividadeVinculadaQuerySet.as_manager()

    def __str__(self):
        return "{}-{}".format(self.rotulo, self.atividade if hasattr(self, "atividade") else '')

    class Meta:
        unique_together = ("atividade", "disciplina_ofertada", "rotulo")

restrito/models/entregas.py
from django.db import models
from django.utils import timezone

class Entrega(models.Model):
    STATUS = (
        ('ENTREGUE', 'Entregue'),
        ('CORRIGIDO', 'Corrigido')
    )

    aluno = models.ForeignKey("contas.Aluno", on_delete=models.PROTECT)
    atividade_vinculada = models.ForeignKey("restrito.AtividadeVinculada", on_delete=models.PROTECT)
    titulo = models.CharField(max_length=255)
    resposta = models.TextField(max_length=500)
    data_entrega = models.DateTimeField(default=timezone.now, editable=False, null=True, blank=True)
    status = models.CharField(max_length=20, default='ENTREGUE', null=True, blank=True, choices=STATUS)
    professor = models.ForeignKey("contas.Professor", default=None, null=True, blank=True ,on_delete=models.PROTECT)
    nota = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    data_avaliacao = models.DateTimeField(default=None, null=True, blank=True)
    obs = models.TextField(max_length=500)

    def __str__(self):
        return '{} - {}'.format(self.aluno, self.titulo)

    class Meta:
        ordering = ['aluno']
        unique_together = ("aluno", "atividade_vinculada")

restrito/models/solicitacoes_matriculas.py
from django.db import models
from django.db.models.query import QuerySet
from django.utils import timezone

from lmsimpacta.utils import get_semestre_atual

class SolicitacaoMatriculaQuery(QuerySet):

    def matriculas_anteriores(self, aluno):
        ano, semestre = get_semestre_atual()
        return self.filter(
            aluno=aluno,
        ).exclude(
            disciplina_ofertada__turma__ano=ano,
            disciplina_ofertada__turma__semestre=semestre
        )

    def matriculas_atuais(self, aluno):
        ano, semestre = get_semestre_atual()
        return self.filter(
            aluno=aluno,
            disciplina_ofertada__turma__semestre=semestre,
            disciplina_ofertada__turma__ano=ano
        )

    def matriculas_aprovadas(self, aluno, ano, semestre):
        return self.annotate(num_alunos=models.Count(
            'aluno',
            filter=models.Q(status='Aprovada')
        )).filter(
            aluno=aluno,
            status='Aprovada',
            disciplina_ofertada__turma__semestre=semestre,
            disciplina_ofertada__turma__ano=ano
        )

class SolicitacaoMatricula(models.Model):
    STATUS = (
        ('Solicitada', 'Solicitada'),
        ('Aprovada', 'Aprovada'),
        ('Reprovada', 'Reprovada')
    )

    aluno = models.ForeignKey("contas.Aluno", models.PROTECT)
    disciplina_ofertada = models.ForeignKey("curriculo.DisciplinaOfertada", models.PROTECT)
    coordenador = models.ForeignKey("contas.Coordenador", models.PROTECT, default=None, blank=True, null=True)
    data = models.DateField(default=timezone.now, blank=True, null=True, editable=False)
    status = models.CharField(max_length=50, default='Solicitada', blank=True, null=True, choices=STATUS)

    objects = SolicitacaoMatriculaQuery.as_manager()

    class Meta:
        verbose_name = 'solicitação de matrícula'
        verbose_name_plural = 'solicitações de matrícula'

restrito/forms.py
from django import forms
from django.contrib.admin import widgets

from bootstrap_datepicker_plus import DateTimePickerInput

from restrito.models import Atividade, AtividadeVinculada, Entrega, SolicitacaoMatricula

class AtividadeForm(forms.ModelForm):

    class Meta:
        model = Atividade
        exclude = ('professor',)

class AtividadeVinculadaForm(forms.ModelForm):

    def __init__(self, professor, *args, **kwargs):
        super(AtividadeVinculadaForm, self).__init__(*args, **kwargs)
        self.fields['atividade'].queryset = Atividade.objects.filter(professor=professor)
        
    class Meta:
        model = AtividadeVinculada
        exclude = ('professor', 'disciplina_ofertada', 'status')
        widgets = {
            'data_inicio': DateTimePickerInput(
                options={
                    "format":"DD/MM/YYYY HH:mm"
                }
            ),
            'data_fim': DateTimePickerInput(
                options={
                    "format":"DD/MM/YYYY HH:mm"
                }
            ),
        }

class EntregaAlunoForm(forms.ModelForm):

    class Meta:
        model = Entrega
        fields = ('titulo', 'resposta')

class SolicitacaoMatriculaForm(forms.ModelForm):
    class Meta:
        model = SolicitacaoMatricula
        fields = ('disciplina_ofertada',)

restrito/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import get_object_or_404, redirect, render

from contas.models import Aluno
from curriculo.models import DisciplinaOfertada as DO
from restrito.forms import AtividadeForm, AtividadeVinculadaForm, EntregaAlunoForm, SolicitacaoMatriculaForm
from restrito.models import Atividade, AtividadeVinculada, Entrega, SolicitacaoMatricula as SM
from lmsimpacta.utils import checa_aluno, checa_professor, get_semestre_atual

@login_required
def home(request):
    ano, semestre = get_semestre_atual()
    cursos = DO.objects.disciplinas_semestre(
        request.user.perfil,
        ano,
        semestre
    )
    context = {
        'ano': ano,
        'semestre': semestre,
        'cursos_atuais': cursos
    }
    return render(request, 'restrito/home.html', context)

@login_required
def turma(request, id_do):
    do = get_object_or_404(DO, id=id_do)
    context = {
        'turma': do,
        'alunos': Aluno.objects.filter(
            solicitacaomatricula__disciplina_ofertada=do,
            solicitacaomatricula__status='Aprovada'
        ),
        'atividades':AtividadeVinculada.objects.listar_atividades_turma(request.user, do)
    }
    return render(request, 'restrito/turma.html', context)

@login_required
@user_passes_test(checa_professor)
def atividade_lista(request):
    context = {
        'atividades': Atividade.objects.filter(professor=request.user.professor)
    }
    return render(request, 'restrito/atividade_lista.html', context)

@login_required
@user_passes_test(checa_professor)
def atividade_form(request, id=None):
    context  = {}
    if id:
        atividade = get_object_or_404(Atividade, id=id)
        context['titulo'] = 'Alterando atividade '+atividade.titulo
    else:
        atividade = None
        context['titulo'] = 'Nova Atividade de Aula'
    form = AtividadeForm(request.POST or None, instance=atividade)

    if request.POST and form.is_valid():
        atividade = form.save(commit=False)
        atividade.professor = request.user.professor
        atividade.save()
        messages.success(request, 'Atividade {} com sucesso!'.format('alterada' if id else 'incluída'))
        nextUrl = request.POST.get("next", "")
        if nextUrl:
            return redirect(nextUrl)
        else:
            return redirect('restrito:atividade_lista')

    context['form'] = form
    return render(request, 'restrito/atividade_form.html', context)

@login_required
@user_passes_test(checa_professor)
def atividade_remover(request, id=None):
    atividade = get_object_or_404(Atividade, id=id)
    atividade.delete()
    messages.success(request, 'Atividade removida com sucesso!')
    return redirect('restrito:atividade_lista')

@login_required
@user_passes_test(checa_professor)
def atividade_vinculada_form(request, id_do, id_vin=None):
    context  = {}
    do = get_object_or_404(DO, id=id_do)
    if id_vin:
        vinc = get_object_or_404(AtividadeVinculada, id=id_vin)
        context["titulo"] = vinc.__str__()
    else:
        vinc = None
        context["titulo"] = 'Nova vinculação de atividade'

    form = AtividadeVinculadaForm(request.user.professor, request.POST or None, instance=vinc)
    if request.POST and form.is_valid():
        vinculada = form.save(commit=False)
        vinculada.professor = request.user.professor
        vinculada.disciplina_ofertada = do
        vinculada.status = 'DISPONIBILIZADA'
        vinculada.save()
        messages.success(request,'Atividade vinculada com sucesso!')
        return redirect('restrito:turma', id_do=id_do)

    context['form'] = form
    return render(request, 'restrito/atividade_vinculada_form.html', context)

@login_required
@user_passes_test(checa_professor)
def atividade_vinculada_remover(request, id_do, id_vin):
    atividade = get_object_or_404(AtividadeVinculada, id=id_vin)
    atividade.delete()
    messages.success(request,'Atividade vinculada removida com sucesso!')
    return redirect('restrito:turma', id_do=id_do)

@login_required
@user_passes_test(checa_professor)
def entrega_listar(request, id_do, id_vin):
    vinculada = get_object_or_404(AtividadeVinculada, id=id_vin)
    entregas = Entrega.objects.filter(atividade_vinculada=vinculada)
    context = {
        "entregas": entregas,
        "atividade": vinculada
    }
    return render(request, 'restrito/entrega_lista.html', context)

@login_required
@user_passes_test(checa_aluno)
def matricula_lista(request):
    ano, semestre = get_semestre_atual()
    context = {
        "ano": ano,
        "semestre": semestre,
        "matriculas": SM.objects.matriculas_atuais(request.user.aluno),
        "matriculas_anteriores": SM.objects.matriculas_anteriores(request.user.aluno)
    }

    return render(request, "restrito/matricula_lista.html", context)

@login_required
@user_passes_test(checa_aluno)
def matricula_solicitar(request, id_do=None):
    context = {}

    if id_do:
        SM.objects.create(
            aluno=request.user.aluno,
            disciplina_ofertada=DO.objects.get(id=id_do)
        )
        messages.success(request, "Matrícula solicitada com sucesso!")
        return redirect("restrito:matricula_lista")
    else:
        context["disciplinas"] = DO.objects.disciplinas_disponiveis(request.user.aluno)
    
    return render(request, "restrito/matricula_solicitar.html", context)

@login_required
@user_passes_test(checa_aluno)
def matricula_remover(request, id_sm):
    sm = get_object_or_404(SM,
        aluno=request.user.aluno,
        id=id_sm,
        status='Solicitada'
    )
    sm.delete()
    messages.success(request, "Matrícula cancelada com sucesso!")
    return redirect("restrito:matricula_lista")
    
@login_required
@user_passes_test(checa_aluno)
def entrega_form(request, id_do, id_vin, id_entrega=None):
    context = {}
    vinculada = get_object_or_404(AtividadeVinculada, id=id_vin)
    entrega = get_object_or_404(Entrega, id=id, aluno=request.user.aluno) if id_entrega else None
    form = EntregaAlunoForm(request.POST or None, instance=entrega)
    if request.POST and form.is_valid():
        entrega = form.save(commit=False)
        entrega.atividade_vinculada = vinculada
        entrega.aluno = request.user.aluno
        entrega.save()
        messages.success(request, 'Entrega realizada com sucesso!')
        return redirect('restrito:turma', id_do=id_do)
    context["form"] = form
    context['atividade'] = vinculada
    return render(request, 'restrito/entrega_form.html', context)

restrito/templates/restrito/atividade_lista.html
{% extends "base.html" %}

{% block titulo %}
    Atividades de Aula
{% endblock titulo %}

{% block main %}
<section class="container container-fluid">
    <h1>Atividades de Aula</h1>
    <a class="btn btn-success my-2" href="{% url 'restrito:atividade_form' %}" role="button">Adicionar</a>
    <ul class="list-group">
        {% for atividade in atividades %}
            <li class="list-group-item d-flex flex-row justify-content-between">
                <div>
                    <div class="d-flex flex-grow-1 justify-content-between">
                        <h2 class="mb-1">{{ atividade.titulo }}</h2>
                        <small>{{ atividade.get_tipo_display }}</small>
                    </div>
                    <p class="mb-1">{{ atividade.descricao }}</p>
                </div>
                <div class="px-3 d-flex flex-column justify-content-around">
                    <a class="btn btn-primary w-100" href="{% url 'restrito:atividade_form' id=atividade.id %}" role="button">Alterar</a>
                    <a class="btn btn-danger w-100" onclick="javascript:confirmarRemocao(event, '{{ atividade }}', this.href);" href="{% url 'restrito:atividade_remover' id=atividade.id %}" role="button">Remover</a>
                </div>
            </li>
        {% empty %}
            <li class="list-group-item alert alert-warning" role="alert">
                Nenhuma atividade criada!
            </li>
        {% endfor %}
    </ul>
</section>
{% endblock main %}

restrito/templates/restrito/atividade_vinculada_form.html
{% extends "base.html" %}

{% block titulo %}
    {{ titulo }}
{% endblock titulo %}

{% block scripts %}
    {{ form.media }}
{% endblock %}

{% block main %}
<h1 class="text-center">
    {{ titulo }}
</h1>
<form method="POST">
    <div class="alert alert-primary" role="alert">
        Não possui atividades cadastradas? Clique <a href="{% url 'restrito:atividade_form' %}?next={{ request.path|urlencode }}" class="alert-link">aqui</a> para incluir uma nova atividade.
    </div>
    {% include "includes/form-group.html" with form=form %}
    <div class="form-group text-center">
        <button type="submit" class="btn btn-primary">Salvar</button>
    </div>
</form>
{% endblock main %}

restrito/templates/restrito/entrega_lista.html
{% extends "base.html" %}

{% block titulo %}
 Entregas de {{ atividade }}
{% endblock titulo %}

{% block main %}
<section class="container">
    <h1>Entregas de {{ atividade }}</h1>
    <ul class="list-group">
        {% for entrega in entregas %}
            <li class="list-group-item d-flex flex-row justify-content-between">
                <div class="d-flex flex-grow-1 justify-content-between">
                    <h2 class="mb-1">{{ entrega }}</h2>
                    <small>{{ entrega.get_status_display }}</small>
                    <p class="w-100">Realizado em {{ entrega.data_entrega }}</p>
                </div>
                <div class="px-3 d-flex flex-column justify-content-around">
                    <a class="btn btn-primary w-100" href="{% url 'restrito:atividade_form' id=atividade.id %}" role="button">Corrigir</a>
                </div>
            </li>
        {% empty %}
            <li class="list-group-item alert alert-warning" role="alert">
                Nenhuma entrega realizada ainda!
            </li>
        {% endfor %}
    </ul>
</section>
{% endblock main %}

restrito/templates/restrito/home.html
{% extends "base.html" %}

{% block titulo %}
Área do {{ user.get_tipo_display }}
{% endblock titulo %}

{% block main %}
<section class="container">
    <div class="p-2 border border-secondary rounded bg-light">
        <h1 class="display-4">Olá {{ user }}</h1>
        <p class="lead">
            <span class="font-weight-bold">E-mail:</span>
            {{ user.perfil.email }}
            <br />
            <span class="font-weight-bold">Celular:</span>
            {{ user.perfil.celular }}
        </p>
    </div>
</section>
<section class="cursos atuais container">
    <h2>Meus cursos de {{ ano }}/{{ semestre }}</h2>
    <div class="card-deck">
        {% for curso in cursos_atuais %}
            <div class="card border-secondary" style="max-width: 18em;">
                <div class="card-body">
                    <h5 class="card-title">{{ curso.disciplina.nome }}</h5>
                    <p class="card-text">{{ curso.num_alunos }} alunos</p>
                    <p class="card-text">
                        <small class="text-muted">
                            {% if curso.ultima_atividade %}
                                Último exercício: {{ curso.ultima_atividade }}
                            {% else %}
                                Nenhuma atividade adicionado
                            {% endif %}
                        </small>
                    </p>
                    <a href="{{ curso.get_absolute_url }}" class="btn btn-primary">Entrar na Turma</a>
                </div>
            </div>
        {% empty %}
            <div class="alert alert-warning" role="alert">
                Você ainda não está matrículado neste semestre!
            </div>
        {% endfor %}
    </div>
</section>
{% endblock main %}

restrito/templates/restrito/matricula_lista.html
{% extends "base.html" %}

{% block titulo %}
    Solicitação de Matrícula
{% endblock titulo %}

{% block main %}
<section class="container container-fluid">
    <h1>Solicitações de Matrícula</h1>
    
    <h2>
        Semestre Atual ({{ semestre }}s{{ ano }})
        <a class="btn btn-success my-2" href="{% url 'restrito:matricula_solicitar' %}" role="button">Solicitar</a>
    </h2>
    
    <ul class="my-2 list-group">
        {% for matricula in matriculas %}
            <li class="list-group-item d-flex flex-wrap flex-row justify-content-between">
                <div class="d-flex flex-grow-1 justify-content-between">
                    <h2 class="mb-1">{{ matricula.disciplina_ofertada.disciplina }}</h2>
                    <small>{{ matricula.disciplina_ofertada.turma }}</small>
                </div>
                <div class="px-3 d-flex flex-column justify-content-around">
                    {% if matricula.status == 'Solicitada' %}
                    <a class="btn btn-danger w-100"
                        onclick="javascript:confirmarRemocao(event, '{{ matricula }}', this.href);"
                        href="{% url 'restrito:matricula_remover' id_sm=matricula.id %}" role="button">
                        Cancelar
                    </a>
                    {% endif %}
                </div>
                <p class="w-100 mb-1">
                    <strong>Professor: </strong> {{ matricula.disciplina_ofertada.professor }}<br/>
                    <strong>Situação: </strong> {{ matricula.get_status_display }}
                </p>
            </li>
        {% empty %}
            <li class="list-group-item alert alert-warning" role="alert">
                Nenhuma matrícula solicitada!
            </li>
        {% endfor %}
    </ul>

    <h2>Matrículas Anteriores</h2>
    <ul class="my-2 list-group">
        {% for matricula in matriculas_anteriores %}
            <li class="list-group-item d-flex flex-row flex-wrap justify-content-between">
                <div class="d-flex flex-grow-1 justify-content-between">
                    <h2 class="mb-1">{{ matricula.disciplina_ofertada.disciplina }}</h2>
                    <small>{{ matricula.disciplina_ofertada.turma }}</small>
                </div>
                <p class="w-100 mb-1">
                    <strong>Professor: </strong> {{ matricula.disciplina_ofertada.professor }}<br/>
                    <strong>Situação: </strong> {{ matricula.get_status_display }}
                </p>
            </li>
        {% empty %}
            <li class="list-group-item alert alert-warning" role="alert">
                Nenhuma matrícula anterior!
            </li>
        {% endfor %}
    </ul>
</section>
{% endblock main %}

restrito/templates/restrito/matricula_solicitar.html
{% extends "base.html" %}

{% block titulo %}
    Nova Matrícula
{% endblock titulo %}

{% block main %}
<section class="container container-fluid">
    <h1 class="text-center">Disciplinas disponíveis para matrícula</h1>
    <ul class="list-group">
        {% for disciplina in disciplinas %}
            <li class="list-group-item d-flex flex-row flex-wrap justify-content-between">
                <div class="d-flex flex-grow-1 justify-content-between">
                    <h2 class="mb-1">{{ disciplina.disciplina }}</h2>
                    <small>{{ disciplina.turma }}</small>
                </div>
                <div class="px-3 d-flex flex-column justify-content-around">
                    <a class="btn btn-success w-100"
                       onclick="javascript:confirmarSolicitacao(event, '{{ disciplina }}', this.href);"
                       href="{% url 'restrito:matricula_solicitar' id_do=disciplina.id %}" role="button">
                       Solicitar
                    </a>
                </div>
                <p class="w-100 mb-1">
                    <strong>Professor: </strong> {{ disciplina.professor }}
                </p>
            </li>
        {% empty %}
            <li class="list-group-item alert alert-warning" role="alert">
                Nenhuma disciplina com matrícula disponível!
            </li>
        {% endfor %}
    </ul>
</section>
{% endblock main %}

restrito/templates/restrito/turma.html
{% extends 'base.html' %}

{% block titulo %}
    {{ turma }}
{% endblock titulo %}

{% block main %}
<section class="container container-fluid">
    <section class="row">
        <h1 class="col-12">
            {{ turma.disciplina }} 
            {{ turma.curso.sigla }}{{ turma.turma.semestre }}{{ turma.turma.nome }} 
            ({{ turma.turma.ano }})
        </h1>
        <p class="col-12">
            Professor: {{ turma.professor }}
        </p>
        <section class="col-sm-4">
            <h2>Alunos</h2>
            <div style="max-height: 500px; overflow: auto;">
                <ul class="list-group">
                    {% for aluno in alunos %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{ aluno.ra}} - {{ aluno.nome}}
                        </li>
                    {% empty %}
                        <div class="alert alert-warning" role="alert">
                            Nenhum aluno matriculado ainda!
                        </div>
                    {% endfor %}
                </ul>
            </div>
        </section>
        <section class="col-sm-8">
            <h2>Atividades</h2>
            {% if user.tipo == 'P' %}
               <a class="btn btn-success mb-2" href="{% url 'restrito:vinculada_form' id_do=turma.id %}" role="button">Vincular uma Atividade</a>
            {% endif %}
            <div style="max-height: 500px; overflow: auto;">
                <ul class="list-group">
                    {% for atividade in atividades %}
                        <li class="list-group-item d-flex flex-row justify-content-between">
                            <div class="flex-grow-1">
                                <div class="d-flex flex-grow-1 justify-content-between">
                                    <h2 class="mb-1">{{ atividade.rotulo }} - {{ atividade.atividade.titulo }}</h2>
                                    <small>{{ atividade.get_status_display }}</small>
                                </div>
                                <p class="mb-1">{{ atividade.atividade.descricao }}</p>
                                <p>De {{ atividade.data_inicio|date:'d/m H:i'  }} até {{ atividade.data_fim|date:'d/m H:i' }}</p>
                                <p>
                                    {{ atividate.entrega }}
                                    {% if user.tipo == 'A' %}
                                    {% elif user.tipo == 'P' %}
                                        Entregas: {{ atividade.entregas }}
                                    {% endif %}
                                </p>
                            </div>
                            <div class="px-3">
                                <div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Ações
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        {% if user.tipo == 'P' %}
                                            <a class="dropdown-item" href="{% url 'restrito:vinculada_form' id_do=turma.id id_vin=atividade.id %}">Alterar</a>
                                            <a class="dropdown-item" onclick="javascript:confirmar(event, '{{atividade}}', this.href);" href="{% url 'restrito:vinculada_remover' id_do=turma.id id_vin=atividade.id %}">Remover</a>
                                            <a class="dropdown-item" href="{% url 'restrito:entrega_lista' id_do=turma.id id_vin=atividade.id %}">Ver Entregas</a>
                                        {% elif user.tipo == 'A' %}
                                            <a class="dropdown-item" href="{% url 'restrito:entrega_form' id_do=turma.id id_vin=atividade.id %}"> Entregar </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% empty %}
                        <div class="alert alert-warning" role="alert">
                            Nenhum atividade vinculada ainda!
                        </div>
                    {% endfor %}
                </ul>
            </div>
        </section>
    </section>
</section>
{% endblock main %}