contas/urls.py
from django.urls import path

from . import views

app_name = 'contas'
urlpatterns = [
    path('entrar/', views.entrar, name='entrar'),
    path('sair/', views.sair, name='sair'),
    path('inscrever/', views.registrar, name='registrar'),
    path('alterar-dados/', views.alterar_dados, name='alterar')
]

curriculo/urls.py
from django.urls import path

from . import views

app_name = 'curriculo'
urlpatterns = [
    path('<str:sigla>/', views.curso, name='curso'),
    path('', views.cursos, name='cursos')
]

lms/urls.py
from django.urls import path

from . import views

app_name = 'lms'
urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contato, name='contato')
]

lmsimpacta/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lms.urls')),
    path('', include('contas.urls')),
    path('cursos/', include('curriculo.urls')),
    path('restrito/', include('restrito.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restrito/urls.py
from django.urls import path

from . import views

app_name = 'restrito'
urlpatterns = [
    path('', views.home, name='home'),
    path('matriculas/', views.matricula_lista, name="matricula_lista"),
    path('matriculas/solicitar/', views.matricula_solicitar, name="matricula_solicitar"),
    path('matriculas/solicitar/<int:id_do>/', views.matricula_solicitar, name="matricula_solicitar"),
    path('matriculas/remover/<int:id_sm>/', views.matricula_remover, name="matricula_remover"),
    path('turma/<int:id_do>/', views.turma, name='turma'),
    path('turma/<int:id_do>/atividade/', views.atividade_vinculada_form, name='vinculada_form'),
    path('turma/<int:id_do>/atividade/<int:id_vin>/', views.atividade_vinculada_form, name='vinculada_form'),
    path('turma/<int:id_do>/atividade/<int:id_vin>/remover/', views.atividade_vinculada_remover, name='vinculada_remover'),
    path('turma/<int:id_do>/atividade/<int:id_vin>/entregas/', views.entrega_listar, name='entrega_lista'),
    path('turma/<int:id_do>/atividade/<int:id_vin>/entregar/', views.entrega_form, name='entrega_form'),
    path('atividades/', views.atividade_lista, name='atividade_lista'),
    path('atividades/form/', views.atividade_form, name='atividade_form'),
    path('atividades/form/<int:id>/', views.atividade_form, name='atividade_form'),
    path('atividades/remover/<int:id>/', views.atividade_remover, name='atividade_remover'),
    
]

contas/models/usuarios.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.shortcuts import reverse
from datetime import date

PERFIS = (
    ('C', 'Coordenador'),
    ('P', 'Professor'),
    ('A', 'Aluno'),
)

class UsuarioManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, login, password=None, **extra_fields):
        if not login:
            raise ValueError('O nome de login é obrigatório')
        login = self.model.normalize_username(login)
        user = self.model(login=login, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, login, password=None, **extra_fields):
        return self._create_user(login, password, **extra_fields)

    def create_superuser(self, login, password, **extra_fields):
        from contas.models import Coordenador
        self.model = Coordenador
        extra_fields.setdefault('tipo', 'C')
        extra_fields.setdefault('nome', login)
        extra_fields.setdefault('celular', login)
        extra_fields.setdefault('email', login)
        return self._create_user(login, password, **extra_fields)

# Create your models here.
class Usuario(AbstractBaseUser):

    login = models.CharField(max_length=100, unique=True)
    password = models.CharField("Senha", max_length=128, db_column="senha")
    dt_expiracao = models.DateField(default=date(year=1900, month=1, day=1), blank=True, null=True)
    tipo = models.CharField(max_length=1, choices=PERFIS)

    USERNAME_FIELD = 'login'
    REQUIRED_FIELDS = []

    objects = UsuarioManager()

    @property
    def is_staff(self):
        return self.tipo == 'C'

    @property
    def perfil(self):
        if self.tipo == 'A':
            return self.aluno
        elif self.tipo == 'P':
            return self.professor
        else:
            return self.coordenador

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_absolute_url(self):
        return self.perfil.get_absolute_url()

lms/models/exceptions.py
class MensagemSemMatriculaException(Exception):
    pass

lms/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail

ASSUNTOS = (
    ('', ' - Selecione um - '),
    ('B', 'Bug'),
    ('R', 'Reclamação'),
    ('S', 'Sugestão')
)

class ContatoForm(forms.Form):

    nome = forms.CharField(
        label="Nome Completo"
    )

    email = forms.EmailField(
        label="E-Mail"
    )

    assunto = forms.ChoiceField(
        label="Assunto",
        choices=ASSUNTOS
    )

    mensagem = forms.CharField(
        label="Mensagem",
        max_length=255,
        widget=forms.Textarea
    )

    def enviar_email(self):
        assunto = self.cleaned_data['assunto']
        send_mail(
            'Mensagem Assunto '+dict(ASSUNTOS)[assunto],
            self.cleaned_data['mensagem'],
            self.cleaned_data['email'],
            [settings.EMAIL_CONTATO]
        )

lms/views.py
from django.shortcuts import render

from .forms import ContatoForm

# Create your views here.
def index(request):
    return render(request, 'index.html')

def contato(request):
    context = {}
    form = ContatoForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            form.enviar_email()
            context['mensagem'] = {
                'texto':'Mensagem enviada com sucesso!',
                'tipo': 'success'
            }
        else:
            context['mensagem'] = {
                'texto': 'Problemas ao enviar a sua mensagem!',
                'tipo': 'danger'
            }
    context["form"] = form
    return render(request, 'contato.html', context)

lms/templates/base.html
{% load static %}

<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="icon" href="{% static 'favicon.ico' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />

  <link rel="stylesheet" href="{% static 'css/site.css' %}">
  {% block links %}{% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/script.js' %}" defer></script>
  <script src="{% static 'js/bootstrapify.js' %}" defer></script>
  {% block scripts %}{% endblock %}

  <title>LMS Impacta - {% block titulo %}{% endblock %}</title>


</head>

<body>
  <header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand text-hide" href="{% url 'lms:index' %}">
        <img src="{% static 'imagens/impacta-logo.png' %}" alt="logo da Impacta" />
        LMS IMPACTA
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="cursosDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Cursos
            </a>
            <div class="dropdown-menu" aria-labelledby="cursosDropdown">
              {% for curso in cursos_menu %}
              <a class="dropdown-item" href="{% url 'curriculo:curso' curso.sigla %}">{{ curso.nome }}</a>
              {% empty %}
              <p class="p-3 text-muted">
                Nenhum curso autorizado no momento!
              </p>
              {% endfor %}
            </div>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'lms:contato' %}">Contato</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          {% if not user.is_authenticated %}
            <li class="nav-item d-flex align-items-center">
              <div class="btn-group" role="group" aria-label="novo usuário">
                <a class="btn btn-outline-success" href="{% url 'contas:registrar' %}">Inscreva-se</a>
                <a class="btn btn-outline-primary" href="{% url 'contas:entrar' %}">Entrar</a>
              </div>
            </li>
          {% else %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                {% if user.tipo == 'A' and user.aluno.foto %}
                  <img src="{% get_media_prefix %}{{ user.aluno.foto }}" class="avatar" alt="foto do usuário" />
                {% else %}
                  <img src="{% static 'imagens/profile.png' %}" class="avatar" alt="foto do usuário" />
                {% endif %}
                {{ user }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ user.get_absolute_url }}">
                  Área do {{ user.get_tipo_display }}
                </a>
                {% if user.tipo == 'P' %}
                  <a class="dropdown-item" href="{% url 'restrito:atividade_lista' %}">Atividades</a>
                {% elif user.tipo == 'A' %}
                  <a class="dropdown-item" href="{% url 'restrito:matricula_lista' %}">Matrícula</a>
                {% endif %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'contas:alterar' %}">Meus Dados</a>
                <a class="dropdown-item" href="{% url 'contas:sair' %}">Sair</a>
              </div>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main role="main">
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}


    {% block main %}

    {% endblock %}
  </main>
  <footer class="text-white bg-secondary mt-3 py-3 px-2">
    <ul class="d-inline-block">
      <li class="d-inline">
        <a href="https://www.facebook.com/FacImpacta/" title="Página do Facebook" class="text-white" target="_blank">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
      <li class="d-inline">
        <a href="https://www.instagram.com/faculdadeimpacta/" class="text-white" title="Instagram" target="_blank">
          <i class="fab fa-instagram"></i>
        </a>
      </li>
      <li class="d-inline">
        <a href="https://www.linkedin.com/edu/faculdade-impacta-tecnologia-161006" class="text-white" title="Linkedin"
          target="_blank">
          <i class="fab fa-linkedin"></i>
        </a>
      </li>
      <li class="d-inline">
        <a href="https://twitter.com/facimpacta" class="text-white" title="Twitter" target="_blank">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
      <li class="d-inline">
        <a href="https://www.youtube.com/user/GrupoImpacta" class="text-white" title="YouTube" target="_blank">
          <i class="fab fa-youtube"></i>
        </a>
      </li>
    </ul>
    <p class="float-right"><a href="#">Topo</a></p>
    <p>{% now 'Y' %} Faculdade Impacta 11 3254-8300 Todos os direitos reservados.</p>
  </footer>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  
</body>

</html>

lms/templates/contato.html
{% extends "base.html" %}

{% block titulo %}
    Contato
{% endblock %}

{% block main %}
<h1 class="text-center">Entre em Contato!</h1>
<form method="POST">
    {% include "includes/form-group.html" with form=form %}
    <div class="form-group text-center">
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>

</form>
{% endblock main %}

lms/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block titulo %}Home{% endblock %}


{% block main %}
<aside class="jumbotron container">
    <h1 class="display-4">Vestibular para o próximo semestre! </h1>
    <p class="lead">Faça já a sua inscrição e garanta o seu futuro.</p>
    <p class="text-center">
        <a class="btn btn-primary btn-lg" href="#" role="button">Inscreva-se Já!</a>
    </p>
</aside>
<section class="container marketing">
    <h1>Prêmios e Reconhecimentos</h1>
    <!-- Three columns of text below the carousel -->
    <div class="card-deck justify-content-around">
        <article class="card text-center bg-dark text-white p-2">
        <img class="card-img-top premio" src="{% static 'imagens/premios/enade-ADM.png' %}" alt="Card image cap">
        <h5 class="card-title">Top 10 ENADE/MEC SP</h5>
        <h6 class="card-subtitle mb-2 text-primary font-weight-bold">Graduação em Administração</h6>
        <p class="card-text">
            Nota 4 na avaliação do MEC – 10.ª maior nota entre as faculdades privadas da cidade de São Paulo.
            </p>
            <p class="card-text"></p>
            3 estrelas na avaliação realizada pelo Guia do Estudante, da Editora Abril, que seleciona os melhores cursos para os estudantes que estão se preparando para o vestibular.
            </p> 
            <p class="card-text"></p>
            Destaque no portal da Revista Exame como o curso que está entre os melhores do Brasil. (06/2017)
        </p>
        <p><a class="btn btn-primary" href="#" role="button">Confira mais sobre o curso</a></p>
        </article><!-- /.col-lg-4 -->
        <article class="card text-center bg-dark text-white p-2">
            <img class="card-img-top premio" src="{% static 'imagens/premios/enade-ADS.png' %}" alt="Card image cap">
            <h5 class="card-title">Maior Nota ENADE SP</h5>
            <h6 class="card-subtitle mb-2 text-primary font-weight-bold">Graduação em Análise e Desenvolvimento de Sistemas</h6>
            <p class="card-text">Nota 4 na avaliação do ENADE/MEC - 1.º melhor curso da cidade de São Paulo.</p>
            <p><a class="btn btn-primary" href="#" role="button">Confira mais sobre o curso</a></p>
        </article><!-- /.col-lg-4 -->
        <article class="card text-center bg-dark text-white p-2">
            <img class="card-img-top premio" src="{% static 'imagens/premios/enade-RD.png' %}" alt="Card image cap">
            <h5 class="card-title">Top 4 ENADE/MEC SP</h5>
            <h6 class="card-subtitle mb-2 text-primary font-weight-bold">Graduação em Redes de Computadores</h6>
            <p class="card-text">Nota 3 na avaliação do ENADE/MEC - 4.º melhor curso da cidade de São Paulo.</p>
        <p><a class="btn btn-primary" href="#" role="button">Confira mais sobre o curso</a></p>
        </article><!-- /.col-lg-4 -->
        <article class="card text-center bg-dark text-white p-2">
            <img class="card-img-top premio" src="{% static 'imagens/premios/enade-SI.png' %}" alt="Card image cap">
            <h5 class="card-title">Top 3 ENADE/MEC SP</h5>
            <h6 class="card-subtitle mb-2 text-primary font-weight-bold">Graduação em Sistemas da Informação</h6>
            <p class="card-text">Nota 4 na avaliação do ENADE/MEC - 3.º melhor curso da cidade de São Paulo.</p>
        <p><a class="btn btn-primary" href="#" role="button">Confira mais sobre o curso</a></p>
        </article><!-- /.col-lg-4 -->
    </div><!-- /.row -->

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
        <h2 class="featurette-heading">Conheça o Smartclass</h2>
        <p class="lead">As salas de aula da Faculdade Impacta são equipadas com lousas eletrônicas, que capturam
            todos os pontos das aulas <strong>presenciais</strong>, como voz, escrita <strong>dinâmica</strong>,
            vídeos e navegação do professor. Todo o conteúdo é gravado e disponibilizado em uma sala de ensino
            virtual para que o aluno assista quando e onde quiser, de qualquer plataforma digital.</p>
        </div>
        <div class="col-md-5">
        <img class="featurette-image img-fluid mx-auto" 
        src="{% static 'imagens/play-smartclass.jpg' %}" alt="play do smartclass">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <h2 class="featurette-heading">Impacta Empreenda 360 Graus</span></h2>
        <p class="lead">
            Por meio da OPE – Oficina Projeto Empresa, que é realizada durante o curso, o aluno tem a oportunidade de construir sua própria startup. O programa de incentivo ao empreendedorismo tem o apoio de grandes nomes do mercado, como a FIESP.
        </p>
        <p class="lead">
            Alguns cases de sucesso já foram realizados por alunos Impacta, como o Projeto “Desperta Saúde” – Universidade São Camilo e Centro Cyber Segurança Impacta.
        </p>
    </div>

    <hr class="featurette-divider">

</section>
{% endblock %}